### ISSUE TITLE
USER STORY: New User Registration 

### ISSUE THREAD

**Issue by vica781** [vica781/Tree-Enthusiast-vica781#1]
As a ***new user***, I want to ***be able to register on the platform***, so that I can ***login and get access.***

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [x] User can register using their full name, email, and password through a registration form on the platform.
- [x] The user receives messages upon both successful and unsuccessful registration attempts.

***

### TASKS
_A single unit of work broken down from the defined user story_

- [x] Design and implement the registration form with front-end validation for full name, email, and password fields.
- [x] Redirect registered user to a landing page.
